version: '2.1'
services:
    mysql:
        image: mysql:5.7.29
        environment:
            MYSQL_DATABASE: ${DB}
            MYSQL_USER: ${DB_USER} 
            MYSQL_PASSWORD: ${DB_PASS}
            restart: 'always'
        container_name: lego_mysql
        networks:
        - backend
        volumes:
            - my-db:/var/lib/mysql

    web:
        image: stakashima21/reviews:latest
        build: .
        environment:
            HOST: ${HOST} 
            DB_USER: ${DB_USER} 
            DB_PASS: ${DB_PASS}
            DB: ${DB}
        container_name: lego_reviews
        networks:
        - frontend
        - backend
        ports:
        - "8080:8080"
        volumes:
             - ${PWD}/:/src/reviews
        depends_on:
        - mysql
    proxy:
        image: stakashima21/reviews-proxy:latest
        build: ../ShojiProxyServer/
        container_name: lego_proxy 
        networks:
        - frontend
        ports:
        - "8000:8000"
        depends_on:
        - web
networks:
    frontend:
    backend:
volumes:
    my-db: {}
